"""
Patristic & Orthodox Christian terminology glossary for EN→ZH subtitle translation.
Compiled from GCDFL (gcdfl.org) and CTCFOL (ctcfol.org) bilingual content.

Sources:
- 3 Maximos Constas lectures (Prayer of Heart, Problem of Thoughts, Unseen Warfare)
- GCDFL QA pages (soteriology, anthropology, sacraments, hierarchy)
- Lydia lectures (Theotokos, Covenant, Bible/Tradition)
- CTCFOL Hesychios of Sinai translation (On Watchfulness and Holiness)
- GCDFL saint hierarchy article
- GCDFL "How can we become God?" article

Convention notes:
- Origen = 奥利金 (NOT 俄利根/厄利根) — user's strict preference
- Nous = 心/心灵 (NOT 理智/灵智 — user deliberately chose 心 as translation)
- Theoria = 静观 (NOT 默观/冥想 — user explicitly rejects 冥想)
- Theosis = 神化 or 成神 (both used in GCDFL/CTCFOL context)
- Philokalia = 爱神集
- Prayer of the Heart = 心祷
- Jesus Prayer = 耶稣祷文
"""

# EN→ZH glossary as a dict, suitable for DeepL glossary API or DSPy signature input
PATRISTIC_GLOSSARY = {
    # === Core theological terms ===
    "theosis": "神化",
    "deification": "神化",
    "theoria": "静观",
    "contemplation": "静观",
    "purification": "净化",
    "illumination": "光照",
    "grace": "恩典",
    "uncreated grace": "非受造之恩",
    "divine light": "神光",
    "transfiguration": "变容",
    "incarnation": "道成肉身",
    "embodiment": "道成肉身",
    "resurrection": "复活",
    "crucifixion": "十字架受难",
    "baptism": "洗礼",
    "chrismation": "傅油礼",
    "holy communion": "圣体圣事",
    "communion": "圣体圣事",
    "eucharist": "圣体圣事",
    "sacrament": "圣事",
    "sacraments": "圣事",
    "divine liturgy": "圣礼仪",
    "liturgy": "礼仪",
    "vigil": "守夜",
    "confession": "告解",
    "repentance": "悔改",
    "prostration": "跪拜",
    "veneration": "敬礼",
    "icon": "圣像",
    "icons": "圣像",
    "candle": "蜡烛",
    "incense": "乳香",

    # === Prayer & spiritual practice ===
    "prayer of the heart": "心祷",
    "prayer of the mind": "心智祈祷",
    "noetic prayer": "灵祷",
    "jesus prayer": "耶稣祷文",
    "prayer rope": "祈祷绳",
    "breathing": "呼吸",
    "meditative": "默念",
    "meditation": "默念",
    "contemplative": "静观的",
    "watchfulness": "警醒",
    "nepsis": "警醒",
    "attention": "专注",
    "stillness": "静谧",
    "hesychia": "静谧",
    "silence": "安静",
    "solitude": "独处",
    "asceticism": "苦修",
    "ascesis": "克修",
    "ascetical": "克修的",
    "spiritual exercise": "灵修操练",
    "spiritual struggle": "属灵争战",
    "spiritual warfare": "属灵争战",
    "unseen warfare": "无形之战",
    "spiritual senses": "灵性感官",
    "inner senses": "内在感官",
    "outer senses": "外在感官",
    "self-activation": "自动祈祷",
    "self-activating": "自动激活",
    "self-negation": "自我否定",
    "self-surrender": "向神降服",
    "self-knowledge": "自我认识",
    "nothingness": "虚无",
    "nullity": "空无",
    "incapacity": "无力",
    "weakness": "软弱",
    "humility": "谦卑",
    "humble": "谦卑",
    "perfection": "完美",
    "virtue": "美德",
    "virtues": "美德",
    "fruits of the spirit": "圣灵的果子",
    "love": "仁爱",
    "joy": "喜乐",
    "patience": "忍耐",
    "kindness": "恩慈",
    "goodness": "良善",
    "faithfulness": "信实",
    "gentleness": "温柔",
    "self-control": "节制",

    # === Passions & vices (the 6-step passion process) ===
    "passion": "情欲",
    "passions": "情欲",
    "dispassion": "无欲",
    "dispassionate": "无欲的",
    "provocation": "挑衅",
    "assault": "攻击",
    "momentary disturbance": "瞬间干扰",
    "coupling": "耦合",
    "communion with thoughts": "与念头联结",
    "assent": "同意",
    "prepossession": "成见",
    "addiction": "成瘾",
    "habit": "习惯",
    "second nature": "第二本性",
    "thought": "念头",
    "thoughts": "念头",
    "logismoi": "妄念",
    "evil thoughts": "邪念",
    "negative thoughts": "消极念头",
    "mental image": "心相",
    "mental representation": "心相",
    "images": "图像",
    "imagination": "幻想",
    "daydream": "白日梦",
    "fantasy": "幻想",
    "stream of consciousness": "念流",
    "consciousness": "意识",
    "memory": "记忆",
    "resentment": "怨恨",
    "attachment": "依恋",
    "obsession": "执念",
    "fixation": "固执",
    "temptation": "诱惑",
    "demonic suggestion": "魔鬼的暗示",
    "devil": "魔鬼",
    "demons": "恶魔",
    "satan": "撒旦",

    # === Anthropology (heart/mind/soul/body) ===
    "heart": "心",
    "mind": "心灵",
    "nous": "心灵",
    "soul": "灵魂",
    "body": "身体",
    "flesh": "肉体",
    "carnal": "属肉体的",
    "carnality": "属肉体",
    "spirit": "灵",
    "spiritual": "属灵的",
    "psychosomatic unity": "心身合一",
    "person": "人",
    "human person": "人",
    "human nature": "人的本性",
    "fallen nature": "堕落本性",
    "free will": "自由意志",
    "will": "意志",
    "human will": "人的意志",
    "divine will": "上帝的旨意",
    "intention": "意图",
    "good disposition": "良好倾向",
    "agency": "主观能动性",
    "self-identity": "自我认同",
    "self": "自我",
    "image of god": "上帝的形象",
    "likeness of god": "上帝的样式",
    "image and likeness": "形象和样式",

    # === Church hierarchy & saints ===
    "church fathers": "教父",
    "fathers": "教父",
    "church": "教会",
    "eastern orthodox": "东正教",
    "orthodox": "东正教",
    "protestant": "新教",
    "roman catholic": "罗马天主教",
    "catholic": "天主教",
    "priest": "神父",
    "bishop": "主教",
    "archbishop": "大主教",
    "archimandrite": "修院院长",
    "monk": "修士",
    "monastery": "修院",
    "monastic": "修道的",
    "monasticism": "修道主义",
    "nun": "修女",
    "laypeople": "平信徒",
    "laity": "平信徒",
    "elder": "长老",
    "spiritual father": "属灵父亲",
    "spiritual director": "灵修指导",
    "confessor": "认信者",
    "martyr": "殉道者",
    "martyrdom": "殉道",
    "saint": "圣人",
    "saints": "圣人",
    "hagiography": "圣徒传记",
    "holy": "圣",
    "blessed": "有福的",

    # === Patristic names (key convention: 奥利金 NOT 俄利根) ===
    "maximus the confessor": "认信者马克西姆",
    "maximos the confessor": "认信者马克西姆",
    "maximos": "马克西姆",
    "maximus": "马克西姆",
    "st maximos": "圣马克西姆",
    "st maximus": "圣马克西姆",
    "fr maximos": "马克西姆神父",
    "fr maximus": "马克西姆神父",
    "origen": "奥利金",
    "st nicodemus": "圣尼哥底母",
    "nicodemus of the holy mountain": "圣山圣尼哥底母",
    "nicodemus": "尼哥底母",
    "st theophan the recluse": "隐士圣西奥凡",
    "theophan": "西奥凡",
    "hesychios of sinai": "西奈的圣赫斯科",
    "hesychios": "赫斯科",
    "st isaac the syrian": "叙利亚的圣以撒",
    "isaac of nineveh": "尼尼微的圣以撒",
    "st isaac": "圣以撒",
    "st basil": "圣巴西尔",
    "basil": "巴西尔",
    "basil the great": "大圣巴西尔",
    "st john chrysostom": "金口约翰",
    "john chrysostom": "金口约翰",
    "chrysostom": "金口约翰",
    "st gregory of nyssa": "尼撒的圣格列高利",
    "gregory of nyssa": "尼撒的格列高利",
    "st gregory": "圣格列高利",
    "gregory": "格列高利",
    "st athanasius": "圣亚他那修",
    "athanasius": "亚他那修",
    "st cyril of jerusalem": "耶路撒冷的圣西里尔",
    "cyril of jerusalem": "耶路撒冷的西里尔",
    "cyril": "西里尔",
    "dionysius": "狄奥尼修斯",
    "dionysius the areopagite": "狄奥尼修斯",
    "evagrius": "艾瓦格瑞",
    "evagrius ponticus": "艾瓦格瑞",
    "diadochos of photiki": "圣希亚多",
    "ignatius of antioch": "安提阿的伊格纳丢",
    "polycarp": "波利卡普",
    "aimilianos": "艾米利安",
    "elder aimilianos": "艾米利安长老",
    # YouTube auto-transcript misheard variants (same person: Elder Aimilianos of Simonopetra)
    "emilianos": "艾米利安",
    "emilionos": "艾米利安",
    "emiliano": "艾米利安",
    "emilio nos": "艾米利安",
    "nicophoros": "尼克弗罗",
    "st nicophoros": "圣尼克弗罗",
    "lorenzo scupoli": "洛伦佐·斯库波利",
    "scupoli": "斯库波利",
    "karl lubavsky": "卡尔·卢巴夫斯基",
    "t.s. eliot": "T.S.艾略特",
    "st augustine": "圣奥古斯丁",
    "augustine": "奥古斯丁",
    "aristotle": "亚里士多德",

    # === Western / Roman saints (from Aug. 10 Laurence hagiography) ===
    "laurence": "劳伦斯",
    "st laurence": "圣劳伦斯",
    "saint laurence": "圣劳伦斯",
    "lawrence": "劳伦斯",
    "st lawrence": "圣劳伦斯",
    "archdeacon": "总执事",
    "sixtus": "西斯笃",
    "pope sixtus": "教宗西斯笃",
    "st sixtus": "圣西斯笃",
    "valerian": "瓦勒良",
    "prefect": "总督",
    "sacred vessels": "圣器",
    "scorpions": "蝎尾鞭",
    "scorpion": "蝎尾鞭",
    "gridiron": "铁栅",
    "iron grill": "铁栅",

    # === Theotokos & Marian terms ===
    "theotokos": "诞神女",
    "virgin mary": "圣母玛利亚",
    "mother of god": "上帝之母",
    "mary": "玛利亚",

    # === Liturgical & sacramental ===
    "pascha": "帕斯哈",
    "easter": "复活节",
    "christos anesti": "基督复活了",
    "forefeast": "节前期",
    "afterfeast": "节后期",
    "feast": "节日",
    "holy week": "圣周",
    "great lent": "大斋期",
    "fasting": "禁食",
    "fast": "禁食",
    "prostration": "跪拜",
    "bowing": "鞠躬",
    "holy baptism": "圣洗",
    "baptismal service": "洗礼仪式",
    "renunciation": "弃绝",
    "renounce satan": "弃绝撒旦",
    "epiclesis": "呼求圣灵",
    "proskomedia": "预备祭",
    "prosphora": "祭饼",
    "antidoron": "祝福饼",
    "holy communion": "圣体圣事",
    "frequent communion": "常领圣餐",
    "mystery": "奥迹",
    "mystagogy": "密仪",
    "mystical": "奥迹的",
    "mystical theology": "密意神学",
    "sacramental": "圣事的",
    "liturgical": "礼仪的",
    "euchologion": "礼仪书",
    "synekdemos": "西尼克德莫斯",
    "hymn": "赞美诗",
    "troparion": "短颂",
    "kontakion": "颂歌",

    # === Biblical & scriptural ===
    "scripture": "圣经",
    "scriptures": "圣经",
    "bible": "圣经",
    "old testament": "旧约",
    "new testament": "新约",
    "gospel": "福音",
    "gospels": "福音书",
    "epistle": "书信",
    "psalm": "诗篇",
    "proverbs": "箴言",
    "genesis": "创世记",
    "exodus": "出埃及记",
    "deuteronomy": "申命记",
    "jeremiah": "耶利米书",
    "ezekiel": "以西结书",
    "sirach": "德训篇",
    "song of songs": "雅歌",
    "revelation": "启示录",
    "ephesians": "以弗所书",
    "galatians": "加拉太书",
    "corinthians": "哥林多书",
    "romans": "罗马书",
    "philippians": "腓立比书",
    "hebrews": "希伯来书",
    "timothy": "提摩太",
    "commandment": "诫命",
    "commandments": "诫命",
    "sin": "罪",
    "sinner": "罪人",
    "sins": "罪",
    "salvation": "救赎",
    "save": "拯救",
    "saved": "得救",
    "kingdom of heaven": "天国",
    "kingdom of god": "上帝的国",
    "heaven": "天",
    "father": "父",
    "our father": "主祷文",
    "lord's prayer": "主祷文",
    "abba father": "阿爸父",
    "son of god": "上帝之子",
    "holy spirit": "圣灵",
    "holy trinity": "三位一体",
    "trinity": "三位一体",
    "trinitarian": "三位一体的",
    "christ": "基督",
    "lord": "主",
    "lord jesus christ": "主耶稣基督",
    "have mercy on me": "请怜悯我",
    "have mercy on me the sinner": "请怜悯我这个罪人",

    # === Philosophical/theological categories ===
    "essence": "本质",
    "nature": "本性",
    "energies": "能量",
    "energy": "能量",
    "hypostasis": "位格",
    "hypostases": "位格",
    "person": "位格",
    "substance": "本体",
    "ousia": "本体",
    "logos": "道",
    "word of god": "上帝之道",
    "logismoi": "妄念",
    "pathos": "情欲",
    "pathoi": "情欲",
    "pragmata": "客观事物",
    "noemata": "心相",
    "prosbole": "挑衅",
    "prosoche": "专注",
    "dianoia": "心智",
    "nepsis": "警醒",
    "apophatic": "否定神学",
    "kataphatic": "肯定神学",
    "apophatic theology": "否定神学",
    "kataphatic theology": "肯定神学",
    "apataxame": "弃绝",
    "syndasurmer": "归向",
    "potential": "潜能",
    "actuality": "实现",
    "potency": "效力",
    "action": "行动",
    "seed": "种子",
    "spark": "火花",
    "ember": "微光",
    "fire": "火",
    "dormant": "休眠",
    "cultivate": "培育",
    "nourish": "滋养",
    "kindle": "点燃",

    # === Salvation & deification process ===
    "adoption": "收养",
    "adopted sons": "收养的儿子",
    "adopted daughters": "收养的女儿",
    "natural son": "亲生儿子",
    "union with god": "与上帝合一",
    "communion with god": "与上帝相交",
    "participation": "参与",
    "participate": "参与",
    "partake": "参与",
    "glorification": "荣耀",
    "glorify": "荣耀",
    "sanctification": "圣化",
    "sanctify": "圣化",
    "transformation": "转变",
    "inner transformation": "内在转变",
    "spiritual life": "属灵生活",
    "spiritual path": "属灵道路",
    "spiritual growth": "属灵成长",
    "spiritual father": "属灵父亲",
    "spiritual experience": "属灵经历",
    "spiritual knowledge": "属灵知识",
    "spiritual vision": "属灵视觉",
    "spiritual eyes": "灵眼",
    "divine glory": "神圣荣耀",
    "divine beauty": "神圣之美",
    "divine nature": "神性",
    "divine presence": "上帝的同在",
    "divine energy": "上帝的能量",
    "divine grace": "上帝的恩典",
    "divine will": "上帝的旨意",
    "divine light": "神光",
    "divine darkness": "神圣黑暗",
    "uncreated": "非受造的",
    "uncreated light": "非受造之光",
    "created": "受造的",
    "creator": "创造者",
    "creation": "受造物",
    "creature": "受造物",
    "created beings": "受造物",

    # === Church history & councils ===
    "ecumenical council": "大公会议",
    "council of trent": "特伦托大公会议",
    "council": "会议",
    "nicene creed": "尼西亚信经",
    "creed": "信经",
    "heresy": "异端",
    "heretical": "异端的",
    "gnosticism": "诺斯替主义",
    "arianism": "阿里乌主义",
    "nestorianism": "聂斯托留异端",
    "nestorius": "聂斯托留",
    "counter-reformation": "反宗教改革",
    "protestant reformation": "新教改革",
    "enlightenment": "启蒙运动",
    "european enlightenment": "欧洲启蒙运动",
    "philokalic revival": "爱神集复兴",
    "ottoman": "奥斯曼土耳其",
    "ottoman turks": "奥斯曼土耳其人",
    "renaissance": "文艺复兴",
    "byzantine": "拜占庭",
    "patristic": "教父的",
    "patristics": "教父学",
    "patristic tradition": "教父传统",
    "early church": "早期教会",
    "early fathers": "早期教父",
    "apostolic": "使徒的",
    "apostles": "使徒",
    "apostolic age": "使徒时代",
    "apostolic fathers": "使徒教父",
    "desert fathers": "沙漠教父",
    "sayings of the desert fathers": "沙漠教父言行录",
    "monastic tradition": "修道传统",
    "hesychast": "静修的",
    "hesychasm": "静修主义",
    "hesychast tradition": "静修传统",
    "philokalia": "爱神集",
    "philokalic": "爱神集的",
    "philokalic library": "菲洛卡利库斯文库",
    "way of a pilgrim": "朝圣者之路",
    "unseen warfare": "无形之战",
    "spiritual combat": "属灵争战",
    "combatimento spirituale": "属灵争战",

    # === Ritual & worship terms ===
    "ritual": "仪礼",
    "ritual space": "仪礼空间",
    "worship": "崇拜",
    "adoration": "敬拜",
    "praise": "赞美",
    "thanksgiving": "感恩",
    "offering": "奉献",
    "sacrifice": "祭献",
    "bloodless sacrifice": "不流血的祭祀",
    "temple": "圣殿",
    "sanctuary": "至圣所",
    "altar": "祭坛",
    "holy place": "圣地",
    "holy of holies": "至圣所",
    "tabernacle": "会幕",
    "covenant": "约",
    "testament": "约",
    "new covenant": "新约",
    "old covenant": "旧约",
    "circumcision": "割礼",
    "passover": "逾越节",
    "pentecost": "五旬节",

    # === Eschatology ===
    "eschaton": "末世",
    "eschatology": "末世论",
    "second coming": "基督再临",
    "parousia": "基督再临",
    "last judgment": "最后审判",
    "eternal life": "永生",
    "eternity": "永恒",
    "heaven": "天堂",
    "kingdom": "国",
    "new heaven and new earth": "新天新地",

    # === Misc recurring terms ===
    "fr": "神父",
    "fr.": "神父",
    "father": "神父",
    "st": "圣",
    "st.": "圣",
    "saint": "圣",
    "holy cross": "圣十字架",
    "cross": "十字架",
    "take up your cross": "背起十字架",
    "garden of gethsemane": "客西马尼园",
    "mount tabor": "他泊山",
    "sinai": "西奈",
    "mount sinai": "西奈山",
    "holy land": "圣地",
    "pilgrimage": "朝圣",
    "pilgrim": "朝圣者",
    "pappas patristic institute": "帕帕斯教父研究所",
    "holy cross greek orthodox school of theology": "圣十字架希腊东正教神学院",
    "st vladimir": "圣弗拉基米尔",
    "st. vladimir's": "圣弗拉基米尔出版社",
    "faber and faber": "法伯与法伯出版社",
    "archimandrite": "修院院长",
    "very rev": "可敬的",
    "very rev.": "可敬的",
    "brother": "兄弟",
    "sister": "姐妹",
    "reader": "读者",
    "dear reader": "亲爱的读者",

    # === Additional terms from full-site scrape (gcdfl.org + ctcfol.org) ===
    # Patristic names (extended)
    "gregory palamas": "帕拉马斯",
    "st gregory palamas": "圣帕拉马斯",
    "palamas": "帕拉马斯",
    "barlaam": "瓦爾拉姆",
    "macarius": "玛卡里奥",
    "st macarius": "圣玛卡里奥",
    "makarios": "玛卡里奥",
    "diadochos": "迪亚多乔",
    "st diadochos": "圣迪亚多乔",
    "diadochos of photiki": "圣迪亚多乔",
    "symeon the new theologian": "新神学家西蒙",
    "john climacus": "约翰克里马克斯",
    "climacus": "克里马克斯",
    "mark the monk": "修士马可",
    "irenaeus": "爱任纽",
    "irenaeus of lyons": "里昂的爱任纽",
    "jerome": "耶柔米",
    "st jerome": "圣耶柔米",
    "gregory thaumaturgus": "陶马图尔古斯",
    "gregory the great": "大格里高利",
    "nicolas cabasilas": "卡巴西拉斯",
    "cabasilas": "卡巴西拉斯",
    "symeon metaphrastis": "梅塔法斯提",
    "justin martyr": "殉道者游斯丁",
    "abba pambo": "潘波阿爸",
    "abba antony": "阿爸安东尼",
    "saint anthony": "圣安东尼",
    "saint cosmas": "圣科斯玛",
    "basil of caesarea": "该撒利亚的巴西尔",
    "gregory of nazianzus": "纳西安的格列高利",
    "st gregory of nazianzus": "纳西安的圣格列高利",
    "st gregory the theologian": "神学家圣格列高利",
    "gregory the sinaite": "西奈的格列高利",
    "john of karpathos": "卡帕索斯的约翰",
    "john of damascus": "大马士革的约翰",
    "john damascene": "大马士革的约翰",
    "andrew of crete": "克里特的安德烈",
    "germanus of constantinople": "君士坦丁堡的哲马努斯",
    "cosmas of maiuma": "马乌马的科斯玛",
    "romanos the melodist": "旋律家罗曼诺斯",
    "ephrem the syrian": "叙利亚的艾弗冷",
    "ephraim the syrian": "叙利亚的艾弗冷",
    "jacob of serug": "萨鲁格的雅各",
    "narsai": "纳尔赛",
    "isaac of nineveh": "尼尼微的以撒",
    "diodochus of photiki": "福提克的迪亚多乔",
    "peter of damascus": "大马士革的彼得",
    "thalassios": "撒拉修",
    "philotheos of sinai": "西奈的斐洛塞奥斯",
    "elias the priest": "祭司伊利亚",
    "theodore the studite": "斯图狄奥斯的狄奥多",
    "theodore studites": "斯图狄奥斯的狄奥多",
    "theophanes the confessor": "认信者狄奥法内",
    "maximos the confessor": "认信者马克西姆",
    "st maximos the confessor": "认信者圣马克西姆",
    "st maximus the confessor": "认信者圣马克西姆",
    "patriarch germanus": "牧首哲马努斯",
    "patriarch photios": "牧首佛提乌",
    "patriarch tarasios": "牧首塔拉修",
    "patriarch nicephoros": "牧首尼克弗罗",

    # Geographical (extended)
    "rome": "罗马",
    "constantinople": "君士坦丁堡",
    "alexandria": "亚历山大",
    "antioch": "安提阿",
    "jerusalem": "耶路撒冷",
    "cappadocia": "加帕多家",
    "cappadocians": "卡帕多西亚三教父",
    "edessa": "埃德萨",
    "nisibis": "尼希比",
    "damascus": "大马士革",
    "byzantium": "拜占庭",
    "ephesus": "以弗所",
    "chalcedon": "迦克墩",
    "nicaea": "尼西亚",
    "athos": "阿索斯",
    "mount athos": "阿索斯山",
    "crete": "克里特",
    "sinai": "西奈",
    "caesarea": "该撒利亚",
    "nazianzus": "纳西安",
    "nyssa": "尼撒",
    "selymbria": "塞林布里亚",
    "pontos": "本都",

    # Church bodies (extended)
    "syrian orthodox church": "叙利亚正教会",
    "assyrian church of the east": "亚述东方教会",
    "church of the east": "东方教会",
    "oriental orthodox": "东方正教",
    "chaldean church": "迦勒底教会",
    "chaldean catholic church": "迦勒底公教会",
    "syriac church": "叙利亚教会",
    "syrian catholic church": "叙利亚公教",
    "maronite church": "马龙派",
    "syro-malabar church": "马拉巴教会",
    "east syriac church": "东叙利亚教会",
    "west syriac church": "西叙利亚教会",
    "east syriac tradition": "东叙利亚传统",
    "nestorian church": "聂斯托利教会",
    "malankara orthodox syrian church": "马拉巴尔正教叙利亚教会",

    # Theological terms (extended)
    "dyophysite": "二性论",
    "monophysite": "一性论",
    "miaphysite": "合性论",
    "dyothelite": "二志论",
    "monothelete": "一志论",
    "theophany": "神显",
    "epiphany": "主显节",
    "koinonia": "共融",
    "theopoiesis": "神化",
    "epektasis": "不断奋进",
    "perichoresis": "互渗互存",
    "consubstantial": "同质",
    "homousios": "同质",
    "theandric": "神人二性",
    "apophthegmata": "教父言行录",
    "gerontikon": "长老录",
    "paterikon": "教父言行录",
    "apatheia": "无欲",
    "christotokos": "基督之母",
    "christ pantocrator": "全能者基督圣像",
    "divine essence": "神圣本质",
    "inner prayer": "心祷",
    "mental prayer": "默祷",
    "pure heart": "清心",
    "praxis": "践行",
    "praktike": "实践",
    "theoretike": "静观",
    "epinoia": "臆想",
    "anapausis": "安息",
    "galene": "宁静",
    "diakrisis": "分辨",
    "discernment": "分辨",
    "discernment of spirits": "辨别诸灵",

    # Liturgical (extended)
    "akathist": "弗座词",
    "akathist hymn": "弗座词",
    "trisagion": "三圣颂",
    "cherubikon": "天使之歌",
    "anaphora": "圣祭礼仪",
    "prokeimenon": "先导颂",
    "alleluia": "阿肋路亚",
    "koinonikon": "领主颂",
    "troparion": "短颂",
    "kontakion": "颂歌",
    "theotokion": "诞神女颂",
    "dogmatic theotokion": "教义性诞神女颂",
    "canon": "圣颂典",
    "eirmos": "起颂",
    "katavasia": "结颂",
    "moleben": "祈祷仪式",
    "panikhida": "追思礼",
    "paraklesis": "祈求礼",
    "communion verse": "圣餐颂",
    "hymnody": "赞美诗",
    "psalmody": "颂咏诗篇",
    "typikon": "礼规",
    "typicon": "礼规",
    "horologion": "时辰颂典",
    "vespers": "晚祷",
    "matins": "晨祷",
    "orthros": "晨祷",
    "compline": "寝前祷",
    "narthex": "门廊",
    "nave": "中殿",
    "iconostasis": "圣像屏",
    "icon screen": "圣像屏",
    "templon": "圣像屏",
    "royal doors": "圣门",
    "holy doors": "圣门",
    "ambo": "讲道台",
    "bema": "圣坛区",
    "apse": "后殿",
    "dome": "穹顶",

    # Church hierarchy (extended)
    "patriarch": "牧首",
    "patriarchate": "牧首区",
    "catholicos": "宗主教",
    "catholicos-patriarch": "牧首",
    "metropolitan": "都主教",
    "auxiliary bishop": "辅理主教",
    "archpriest": "大神父",
    "hieromonk": "修士司祭",
    "hieromonk isaac": "修士司祭以撒",
    "schema-monk": "琪玛修士",
    "schema": "琪玛",
    "lavra": "大劳拉",
    "great lavra": "大劳拉修道院",
    "skete": "斯科提",
    "stoudios monastery": "斯图狄奥斯修道院",

    # Councils (extended)
    "council of ephesus": "以弗所会议",
    "council of chalcedon": "迦克墩会议",
    "council of nicaea": "尼西亚会议",
    "council of trent": "特伦托会议",
    "council of ferrara-florence": "佛罗伦萨大公会议",

    # Languages & texts (extended)
    "syriac": "叙利亚文",
    "aramaic": "亚兰文",
    "sogdian": "粟特语",
    "sogdians": "粟特人",
    "septuagint": "七十士译本",
    "lxx": "七十士译本",
    "vulgate": "武加大译本",
    "peshitta": "别西塔",
    "deutero-canonical": "次经",
    "deuterocanonical": "次经",
    "apocrypha": "次经",

    # Feasts (extended)
    "dormition": "安息",
    "dormition of the theotokos": "诞神女安息",
    "annunciation": "天使报喜",
    "nativity": "圣诞",
    "transfiguration": "变容",
    "theophany": "神显",

    # Virtues & vices (extended)
    "gluttony": "贪食",
    "lust": "色欲",
    "avarice": "贪财",
    "hatred": "憎恨",
    "sorrow": "忧愁",
    "acedia": "懈怠",
    "vainglory": "虚荣",
    "pride": "骄傲",

    # Misc from corpus
    "passion bearers": "受难者",
    "martyrium": "纪念堂",
    "christendom": "基督教王国",
    "heresy or schism": "异端或分裂",
    "neo-patristic synthesis": "新教父精神",
    "spiritual exegesis": "灵意释经",
    "spiritual writers": "灵修作家",
    "letter to spirit": "字句到灵意",
    "person-hypostasis": "位格",
    "spirits": "灵体",
    "holy days": "圣日",
    "paschal": "帕斯哈的",
    "origenist": "奥利金派",
    "school of edessa": "埃德萨学园",
    "christology": "基督论",
    "soteriology": "救恩论",
    "ecclesiology": "教会论",
    "anthropology": "人论",
    "eschatology": "末世论",
    "triadology": "三位一体论",
    "mariology": "圣母论",
    "pneumatology": "圣灵论",
    "mystagogy": "密仪",
    "mystical theology": "密意神学",

    # === Recent GCDFL / CTCFOL additions: names, places, works, and specialist terms ===
    # Patristic, Syriac, and modern Christian-study names
    "ephrem": "叙利亚的圣艾弗冷",
    "aphrahat": "阿弗哈特",
    "theodore of mopsuestia": "摩普绥提亚的狄奥多",
    "bardaisan": "巴代桑",
    "narsai": "纳尔赛",
    "simeon stylites": "石柱西蒙",
    "symeon the holy fool": "圣愚西蒙",
    "macrina": "玛卡瑞娜",
    "ambrose": "安波罗修",
    "tertullian": "德尔图良",
    "cyprian": "居普良",
    "hilary of poitiers": "普瓦捷的希拉里",
    "john cassian": "卡西安",
    "john solheid": "索尔海德",
    "sebastian brock": "塞巴斯蒂安·布洛克",
    "edmund beck": "埃德蒙德·贝克",
    "kallistos ware": "卡里斯托·维尔",
    "callistos ware": "卡里斯托·维尔",

    # Syriac and late-antique places and regions
    "mesopotamia": "美索不达米亚",
    "syria": "叙利亚",
    "persia": "波斯",
    "iraq": "伊拉克",
    "turkey": "土耳其",
    "ctesiphon": "泰锡封",
    "seleucia": "塞琉西亚",
    "tur abdin": "图尔阿卜丁",
    "mardin": "马尔丁",

    # Named Christian and patristic works
    "hymns on paradise": "天堂之歌",
    "hymns of faith": "信心之歌",
    "book of steps": "步书",
    "liber graduum": "步书",
    "demonstrations": "论证集",
    "odes of solomon": "所罗门诗歌",
    "acts of thomas": "多马行传",
    "city of god": "上帝之城",
    "on the trinity": "论三位一体",
    "confessions": "忏悔录",
    "on free will": "论自由意志",
    "longer rules": "长会规",

    # Theological, liturgical, and spiritual-study terms
    "apokatastasis": "万物复兴",
    "anagogy": "灵意阐释",
    "antiochene christology": "安提阿派基督论",
    "filioque": "和子句",
    "hesychast controversy": "静修之争",
    "coenobium": "共住修道院",
    "eremitic": "隐修的",
    "antiphon": "对唱圣咏",
    "diptych": "双联画",
    "lectionary": "诵经集",
    "madrasha": "律诗",

    # Vespers order (黄昏礼-附和合本诗篇-颂唱省略-08-10补充修订用.docx)
    "octoechos": "八调集",
    "plagal tone": "辅调",
    "menaion": "月颂集",
    "apolytikion": "遣散词",
    "apolytikia": "遣散词",
    "opening psalm": "开篇圣咏",
    "lamp-lighting prayers": "灯台祷文",
    "great litany": "平安连祷",
    "litany of supplication": "恳求连祷",
    "o gladsome light": "禧光颂",
    "phos hilaron": "禧光颂",
    "evening prokeimenon": "黄昏先导颂",
    "song of simeon": "西缅之歌",
    "nunc dimittis": "西缅之歌",
    "stichos": "节",
    "deacon": "辅祭",
    "choir": "唱诗班",
    "proestos": "主礼",
    "holy table": "圣祭台",
    "ever-virgin": "永贞童女",
    "cyril of alexandria": "亚历山大的圣西里尔",
    "prooimiakos psalm": "开篇圣咏",
    "lucernarion": "灯台礼",
    "lychnikon": "灯台祷文",
    "eirenika": "平安连祷",
    "great ektenia": "平安连祷",
    "litany of peace": "平安连祷",
    "plerotika": "恳求连祷",
    "ektenia": "连祷",
    "ektenes litany": "恳切连祷",
    "vesperal entrance": "黄昏入堂",
    "eisodos": "入堂",
    "priestly exclamation": "高声祷词",
    "ekphonesis": "高声祷词",
    "dismissal": "遣散礼",
    "apolysis": "遣散礼",
    "liturgical reader": "宣读者",
    "kyrie eleison": "求主怜悯",
    "lord i have cried": "主啊，我呼求你",
    "vesperal sacrifice": "晚祭",
    "incense offering": "香祭",
    "god-receiver": "上帝接纳者",
}


def get_glossary_for_dspy():
    """Return glossary as a formatted string for DSPy signature input."""
    pairs = []
    for en, zh in sorted(PATRISTIC_GLOSSARY.items()):
        pairs.append(f"{en}={zh}")
    return "; ".join(pairs)


def get_relevant_glossary_terms(en_text, min_len=3):
    """Return glossary entries whose EN term appears in en_text (case-insensitive,
    plural-aware). Used to pass only relevant terms to the DSPy signature, keeping
    token cost low while ensuring the LLM sees correct ZH for names/terms in context.

    Returns a formatted string like "monk=修士; monastery=修院" or "" if no matches.
    """
    import re as _re

    matches = []
    for en_term, zh_term in sorted(PATRISTIC_GLOSSARY.items(), key=lambda kv: len(kv[0]), reverse=True):
        if len(en_term) < min_len:
            continue
        # word-boundary, plural-aware (same logic as _compile_term_matcher in subtitle.py)
        if en_term.endswith("y"):
            stem = en_term[:-1]
            pat = rf"\b{_re.escape(en_term)}\b|\b{_re.escape(stem)}ies\b"
        else:
            pat = rf"\b{_re.escape(en_term)}s?\b"
        if _re.search(pat, en_text, _re.IGNORECASE):
            matches.append(f"{en_term}={zh_term}")
    return "; ".join(matches)


def get_glossary_for_deepl():
    """Return glossary as a list of (en, zh) tuples for DeepL glossary API."""
    return [(en, zh) for en, zh in sorted(PATRISTIC_GLOSSARY.items())]


if __name__ == "__main__":
    print(f"Total glossary entries: {len(PATRISTIC_GLOSSARY)}")
    # Quick validation: no empty values
    for en, zh in PATRISTIC_GLOSSARY.items():
        assert en and zh, f"Empty entry: {en!r} = {zh!r}"
    print("All entries valid (non-empty)")
    print("\nSample (first 10):")
    for en, zh in list(sorted(PATRISTIC_GLOSSARY.items()))[:10]:
        print(f"  {en} = {zh}")
