output_dir: "/path/to/output"
transcribe_model: "large-v3"
inputs:
  - input: "video1.mp4"
    title: "First Segment"
    start_time: "00:10:00"
    end_time: "00:20:00"
  - input: "video2.mp4"
    title: "Second Segment"
    start_time: "00:05:00"
    end_time: "00:15:00"
