output_dir: "./output"
transcribe_model: "large-v3"
input: "/home/ajiap/Documents/GCDFL-shared/Ware2-18-2025-05-02-Liturgy2.mp4"
segments:
          - start_time: "00:01:42"
            end_time: "00:05:10"
            title: "恩典为何是通过可见的礼仪来传递的？身体和灵魂都领受神恩"
          - start_time: "00:07:45"
            end_time: "00:12:40"
            title: "东正教有哪些圣礼？"
          - start_time: "00:13:56"
            end_time: "00:16:00"
            title: "为什么礼仪的举行与使徒统绪有关？神的物是什么？"
          - start_time: "00:16:10"
            end_time: "00:21:00"
            title: "东正教的洗礼是怎样的？"
          - start_time: "00:21:06"
            end_time: "00:24:47"
            title: "东正教的傅油礼是怎样的？"
          - start_time: "00:24:47"
            end_time: "00:26:57"
            title: "东正教如何接受转宗者？"
          - start_time: "00:27:28"
            end_time: "00:32:52"
            title: "东正教的圣餐礼概览"
          - start_time: "00:34:18"
            end_time: "00:35:52"
            title: "为何在圣餐礼中呼求圣灵转变饼和酒是重要的？"
          - start_time: "00:36:01"
            end_time: "00:42:06"
            title: "东正教如何看待变质说？"
          - start_time: "00:38:21"
            end_time: "00:39:02"
            title: "维尔主教：地方会议权威不如大公会议，且是可选择性的"
          - start_time: "00:45:00"
            end_time: "00:46:05"
            title: "东正教如何领圣餐？"
          - start_time: "00:47:00"
            end_time: "00:51:34"
            title: "东正教的忏悔礼是怎样的？"
          - start_time: "00:52:10"
            end_time: "00:57:32"
            title: "为什么传统教会与新教选择和按立神职人员有很大区别？"
          - start_time: "00:57:34"
            end_time: "01:00:14"
            title: "东正教的神父要求竟然这么严？主教为什么要求独身？"
          - start_time: "01:04:25"
            end_time: "01:05:45"
            title: "为何东正教女信徒不能成为神父？"
          - start_time: "01:06:05"
            end_time: "01:09:42"
            title: "女性在教会中的作用是什么？地位平等，分工不同，各司其职"
          - start_time: "01:16:12"
            end_time: "01:18:00"
            title: "神父被辞退后，还能再入神职吗？"
          - start_time: "01:19:15"
            end_time: "01:23:32"
            title: "为何教规如此复杂，难以实践？"
          - start_time: "01:24:00"
            end_time: "01:26:04"
            title: "为什么不建议一个神父在一个教派被罢免后，去另一个教派再入神职？"
          - start_time: "01:26:19"
            end_time: "01:29:19"
            title: "为什么要慢慢传讲东方教会的传统？好事多磨"
