# Wenbi configuration file

# Global defaults
defaults:
  output_dir: "output"
  rewrite_llm: "gpt-4"
  translate_llm: "gpt-3.5-turbo"
  transcribe_lang: "en"
  translate_lang: "Chinese"
  rewrite_lang: "Chinese"
  multi_language: false
  chunk_length: 8
  max_tokens: 50000
  timeout: 3600
  temperature: 0.1
  base_url: "http://localhost:11434"
  transcribe_model: "large-v3-turbo"

# Input files/URLs with optional specific configurations
inputs:
  - path: "video1.mp4"
    output_dir: "output/video1"
    transcribe_lang: "ja"
    
  - path: "https://example.com/video2"
    output_dir: "output/video2"
    translate_lang: "English"
    
  - path: "audio.mp3"
    # Will use default settings if not specified
